server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: userCommandApi
          uri: http://localhost:8081/api/v1/users/**
          predicates:
            - Path=/api/v1/users/**

        - id: userQueryApi
          uri: http://localhost:8082/api/v1/users/**
          predicates:
            - Path=/api/v1/users/**