version: '3.8'
services:
  # Mongo DB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jincrates
      - MONGO_INITDB_ROOT_PASSWORD=jincrates
    volumes:
      - "./volumes/mongodb:/data/db"
    networks:
      - backend

  # Maria DB
  mariadb:
    image: mariadb:11.1.2
    container_name: mariadb
    hostname: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./volumes/mariadb/conf.d:/etc/mysql/conf.d"
      - "./volumes/mariadb:/data/db"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: master
      MARIADB_USER: jincrates
      MARIADB_PASSWORD: jincrates
    networks:
      - backend

  # Axon Server
  axon-server:
    image: axoniq/axonserver:latest
    container_name: axon-server
    restart: always
    ports:
      - "8024:8024"
      - "8124:8124"
    networks:
      - backend

networks:
  backend:
    driver: bridge