### 유저 등록
POST http://localhost:8000/api/v1/users/register
Content-Type: application/json

{
  "id": "",
  "user": {
    "name": "name",
    "account": {
      "username": "username@email.com",
      "password": "Passw0rd",
      "roles": [
        "WRITE_PRIVILEGE"
      ]
    }
  }
}
